### ISSUE TITLE
attribute lang=en in template.html?

### ISSUE THREAD

**Issue by tidiview** [kaisermann/sapper-template-i18n#1]
Hi.
How do you plan to deal with the attribute `lang=en` in the `html` tag of `template.html`?
It needs to be reflecting a locale, doesn't it?

**Comment by tidiview** [comment]
in code you can do document.documentElement.setAttribute('lang', 'ik')
you can make that reactive as well: $: document.documentElement.setAttribute('lang', lang)

**Comment by kaisermann** [comment]
Hey @tidiview 👋  `svelte-i18n` already [does that](https://github.com/kaisermann/svelte-i18n/blob/master/src/runtime/stores/locale.ts#L56) whenever the locale changes. The only problem right now is that we need a way to pass that value during SSR.

**Comment by DerpDays** [comment]
I feel like the SSR side of this still needs addressing so it might be best to reopen this for now?
