### ISSUE TITLE
This part cause an error 500 in the Service-worker section when using Sapper with Rollup in

### ISSUE THREAD

**Issue by ktryndchrs** [kaisermann/sapper-template-i18n#4]
**The code that create the problem**
https://github.com/kaisermann/sapper-template-i18n/blob/25d44b68c23901034984387e22924a4c36319925/src/i18n.js#L61-L70

**The Service-Worker error**:
```
┌─────────────────────┐
│ built serviceworker │
└─────────────────────┘
   1.34 kB service-worker.js
           │ src/service-worker.js (79.9%)
           └ src/node_modules/@sapper/service-worker.js (20.1%)

> Built in 2.7s
> Crawling http://localhost:3000/
       41 B   (500)  <=== RIGHT HERE
   1.22 kB   service-worker-index.html
```

**My setup file:**
[Sapper-i18n-Rollup.zip](https://github.com/kaisermann/sapper-template-i18n/files/4910334/Sapper-i18n-Rollup.zip)

**Personnal note**
I tried my best to find the solution b8t my knowledge is quite limited. I simply commented this part for the moment as a temporary fix until I (or someone else) find the solution to it!

**Comment by raduab** [comment]
I found a fix: https://github.com/kaisermann/sapper-template-i18n/pull/6

**Comment by kaisermann** [comment]
🎉
